// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "TXSBufferList.h"


@implementation TXSBufferList

- (nonnull instancetype)initWithItems:(nonnull NSArray *)items
{
    if (self = [super init]) {
        _items = items;
    }
    return self;
}

+ (nonnull instancetype)bufferListWithItems:(nonnull NSArray *)items
{
    return [[self alloc] initWithItems:items];
}

@end
