// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "TXSBufferList.h"
#include "../buffer_list.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TXSBufferList;

namespace djinni_generated {

struct BufferList
{
    using CppType = ::textsort::BufferList;
    using ObjcType = TXSBufferList*;

    using Boxed = BufferList;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
