// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "TXSBufferList+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto BufferList::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::List<::djinni::Binary>::toCpp(obj.items)};
}

auto BufferList::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[TXSBufferList alloc] initWithItems:(::djinni::List<::djinni::Binary>::fromCpp(cpp.items))];
}

}  // namespace djinni_generated
