// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <Foundation/Foundation.h>

@interface TXSBufferList : NSObject
- (nonnull instancetype)initWithItems:(nonnull NSArray *)items;
+ (nonnull instancetype)bufferListWithItems:(nonnull NSArray *)items;

@property (nonatomic, readonly, nonnull) NSArray * items;

@end
