// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "TXSBufferList.h"
#import "TXSItemList.h"
#import "TXSSortOrder.h"
#import <Foundation/Foundation.h>
@class TXSSortItems;
@protocol TXSTextboxListener;


@interface TXSSortItems : NSObject

/** Interface for iOS / Android demo */
- (void)sort:(TXSSortOrder)order
       items:(nonnull TXSItemList *)items;

+ (nullable TXSSortItems *)createWithListener:(nullable id<TXSTextboxListener>)listener;

/** Interface for localhost demo */
+ (void)runSortItems:(nonnull TXSItemList *)items;

+ (void)runSortBuffers:(nonnull TXSBufferList *)items;

@end
