// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include "NativeBufferList.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeBufferList::NativeBufferList() = default;

NativeBufferList::~NativeBufferList() = default;

auto NativeBufferList::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeBufferList>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::List<::djinni::Binary>::fromCpp(jniEnv, c.items)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeBufferList::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeBufferList>::get();
    return {::djinni::List<::djinni::Binary>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mItems))};
}

}  // namespace djinni_generated
