// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "buffer_list.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeBufferList final {
public:
    using CppType = ::textsort::BufferList;
    using JniType = jobject;

    using Boxed = NativeBufferList;

    ~NativeBufferList();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeBufferList();
    friend ::djinni::JniClass<NativeBufferList>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/textsort/BufferList") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/ArrayList;)V") };
    const jfieldID field_mItems { ::djinni::jniGetFieldID(clazz.get(), "mItems", "Ljava/util/ArrayList;") };
};

}  // namespace djinni_generated
