// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <cstdint>
#include <utility>
#include <vector>
class BufferList; // Requiring extended class

namespace textsort {

struct BufferListBase {
    std::vector<std::vector<uint8_t>> items;

    BufferListBase(std::vector<std::vector<uint8_t>> items)
    : items(std::move(items))
    {}

    virtual ~BufferListBase() = default;

protected:
    BufferListBase(const BufferListBase&) = default;
    BufferListBase(BufferListBase&&) = default;
    BufferListBase& operator=(const BufferListBase&) = default;
    BufferListBase& operator=(BufferListBase&&) = default;
};

}  // namespace textsort
