// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package com.dropbox.textsort;

import java.util.ArrayList;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class BufferListBase {


    /*package*/ final ArrayList<byte[]> mItems;

    public BufferListBase(
            @Nonnull ArrayList<byte[]> items) {
        this.mItems = items;
    }

    @Nonnull
    public ArrayList<byte[]> getItems() {
        return mItems;
    }
}
